# Dependencies
markdown:         redcarpet
highlighter:         rouge

# Permalinks
permalink:        none

# Setup
title:            A million rabbit holes
tagline:          ""
description:      ''
url:              http://amillionrabbitholes.com
baseurl:          '/'
paginate:         5

author:
  name:           'Enric Lluelles'
  url:            https://enric.lluell.es

twitter_url:    http://twitter.com/enriclluelles
github_url:    https://github.com/enriclluelles
